# Generated by Django 4.1.2 on 2022-10-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='men',
            options={'ordering': ['id'], 'verbose_name': 'Известные мужчины', 'verbose_name_plural': 'Известные мужчины'},
        ),
    ]
